apiVersion: v1
kind: ConfigMap
metadata:
  name: customer
data:
  application.properties: |-
    spring.sleuth.sampler.probability=1
    spring.zipkin.baseUrl=http://zipkin:9411/
    spring.zipkin.sender.type=web
    
    logging.file.name=logs/customer/customer.log

    spring.datasource.url=jdbc:mysql://mysql-customer:3308/microservices?useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    spring.datasource.username=user
    spring.datasource.password=password
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.hikari.maximum-pool-size=5
  
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=create
    spring.jpa.defer-datasource-initialization=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    spring.jpa.properties.hibernate.format_sql=true
  
    spring.sql.init.mode=always
  
    spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8090/auth/realms/spring-microservice
    spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8090/auth/realms/spring-microservice/protocol/openid-connect/certs