apiVersion: v1
kind: ConfigMap
metadata:
  name: order
data:
  application.properties: |-
    spring.sleuth.sampler.probability=1
    spring.zipkin.baseUrl=http://zipkin:9411/
    spring.zipkin.sender.type=web

    app.client.products.host=http://product
    app.client.customers.host=http://customer
    app.client.orders.host=http://order
    
    logging.file.name=logs/order-graphql/order-graphql.log
  
    spring.graphql.graphiql.enabled=true
  
    spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8090/auth/realms/spring-microservice
    spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8090/auth/realms/spring-microservice/protocol/openid-connect/certs
  
    resilience4j.circuitbreaker.instances.customer.registerHealthIndicator=true
    resilience4j.circuitbreaker.instances.customer.slidingWindowSize=10
    resilience4j.circuitbreaker.instances.customer.minimumNumberOfCalls=7
    resilience4j.circuitbreaker.instances.customer.failureRateThreshold=60
    resilience4j.circuitbreaker.instances.customer.slowCallDurationThreshold=10s
    resilience4j.circuitbreaker.instances.customer.permittedNumberOfCallsInHalfOpenState=3
    resilience4j.circuitbreaker.instances.customer.waitDurationInOpenState=1m
    resilience4j.circuitbreaker.instances.customer.ignoreExceptions[0]=com.my.app.model.exception.ApiClientErrorException
  
    resilience4j.circuitbreaker.instances.product.registerHealthIndicator=true
    resilience4j.circuitbreaker.instances.product.slidingWindowSize=10
    resilience4j.circuitbreaker.instances.product.minimumNumberOfCalls=7
    resilience4j.circuitbreaker.instances.product.failureRateThreshold=60
    resilience4j.circuitbreaker.instances.product.slowCallDurationThreshold=10s
    resilience4j.circuitbreaker.instances.product.permittedNumberOfCallsInHalfOpenState=3
    resilience4j.circuitbreaker.instances.product.waitDurationInOpenState=1m
    resilience4j.circuitbreaker.instances.product.ignoreExceptions[0]=com.my.app.model.exception.ApiClientErrorException
    
    resilience4j.circuitbreaker.instances.order.registerHealthIndicator=true
    resilience4j.circuitbreaker.instances.order.slidingWindowSize=10
    resilience4j.circuitbreaker.instances.order.minimumNumberOfCalls=7
    resilience4j.circuitbreaker.instances.order.failureRateThreshold=60
    resilience4j.circuitbreaker.instances.order.slowCallDurationThreshold=10s
    resilience4j.circuitbreaker.instances.order.permittedNumberOfCallsInHalfOpenState=3
    resilience4j.circuitbreaker.instances.order.waitDurationInOpenState=1m
    resilience4j.circuitbreaker.instances.order.ignoreExceptions[0]=com.my.app.model.exception.ApiClientErrorException