apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-logs-volume
  labels:
    type: local
spec:
  storageClassName: shared-logs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-logs-volume-claim
spec:
  storageClassName: shared-logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi