apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: artsiombarodka/order:layered
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          args: [
            "--spring.cloud.kubernetes.config.name=order",
            "--spring.cloud.loadbalancer.ribbon.enabled=false",
            "--spring.cloud.discovery.locator.enabled=true",
            "--spring.cloud.kubernetes.loadbalancer.enabled=true",
            "--spring.cloud.kubernetes.enabled=true",
            "--logging.file.name=logs/order/order.log"]
          volumeMounts:
            - mountPath: /opt/logs
              name: shared-logs-volume
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            failureThreshold: 30
            periodSeconds: 40
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            failureThreshold: 2
            periodSeconds: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            failureThreshold: 2
            periodSeconds: 3
            successThreshold: 1
      restartPolicy: Always
      volumes:
        - name: shared-logs-volume
          persistentVolumeClaim:
            claimName: shared-logs-volume-claim