apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: artsiombarodka/order:layered
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /opt/logs
              name: shared-logs-volume
          envFrom:
            - secretRef:
                name: order
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            failureThreshold: 30
            periodSeconds: 40
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            failureThreshold: 2
            periodSeconds: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            failureThreshold: 2
            periodSeconds: 3
            successThreshold: 1
      restartPolicy: Always
      volumes:
        - name: shared-logs-volume
          persistentVolumeClaim:
            claimName: shared-logs-volume-claim