apiVersion: v1
kind: ConfigMap
metadata:
  name: product-search
data:
  application.properties: |-
    spring.cloud.loadbalancer.ribbon.enabled=false
    spring.cloud.discovery.locator.enabled=true
    spring.cloud.kubernetes.loadbalancer.enabled=true
    spring.cloud.kubernetes.enabled=true
    
    spring.sleuth.sampler.probability=1
    spring.zipkin.baseUrl=http://zipkin:9411/
    spring.zipkin.sender.type=web
    spring.sleuth.messaging.kafka.enabled=true
    
    spring.batch.job.enabled=true
    
    app.elasticSearch.uri=elasticsearch:9200
    app.products.data.path=data/products_data.csv
    
    kafka.productSearch.bootstrapAddress=kafka:9092
    kafka.productSearch.groupId=order-orchestrator
    kafka.productSearch.topic.product.name=product
    kafka.productSearch.topic.product.partitions=3
    kafka.productSearch.consumer.product.count=3
  
    spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8090/auth/realms/spring-microservice
    spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8090/auth/realms/spring-microservice/protocol/openid-connect/certs